name: ci-setup

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "setup Python ${{ inputs.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: install project
        run: uv sync --locked --all-extras --dev && uv pip install -e .
