name: ci

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: setup
        uses: ./.github/actions/ci-setup/
        with:
          python-version: ${{ matrix.python-version }}

      - name: cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-4|${{ env.pythonLocation }}|

      - name: run pre-commit
        run: uv run pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: setup
        uses: ./.github/actions/ci-setup/
        with:
          python-version: ${{ matrix.python-version }}

      - name: run pytest
        run: uv run pytest
