name: ci

on:
  push:

jobs:
  pre-commit:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          "3.11"
        ]
    uses: ./.github/workflows/ci-setup.yml
    with:
      python-version: ${{ matrix.python-version }}
    steps:
      - name: cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-4|${{ env.pythonLocation }}|

      - name: run pre-commit
        run: uv run pre-commit run --all-files

  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          "3.11"
        ]
    uses: ./.github/workflows/ci-setup.yml
    with:
      python-version: ${{ matrix.python-version }}
    steps:
      - name: run pytest
        run: uv run pytest
