name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feat

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: .github/workflows/setup-project
        with:
          python-version: "${{ matrix.python-version }}"

      - name: run pre-commit
        run: uv run pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: .github/workflows/setup-project
        with:
          python-version: "${{ matrix.python-version }}"

      - name: run pytest
        run: uv run pytest
