name: ci

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "setup Python ${{ inputs.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: install project
        run: uv sync --locked --all-extras --dev

  pre-commit:
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - name: run pre-commit
        run: uv run pre-commit run --all-files

  pytest:
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - name: run pytest
        run: uv run pytest
