name: setup-project
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "setup Python {% raw %}${{ inputs.python-version }}{% endraw %}"
        uses: actions/setup-python@v5
        with:
          python-version: "{% raw %}${{ inputs.python-version }}{% endraw %}"

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: install project
        run: uv sync --locked --all-extras --dev
